[package]
name = "ocilot-oci"
version = "0.1.0-pre"
license = "Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
oci-distribution = "0.8"

[dependencies.ocilot-core]
path = '../core'
